/**
 * NodeCMS
 * API for Node Content Management System
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/SiteMeta'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/SiteMeta'));
  } else {
    // Browser globals (root is window)
    if (!root.NodeCms) {
      root.NodeCms = {};
    }
    root.NodeCms.SiteApi = factory(root.NodeCms.ApiClient, root.NodeCms.SiteMeta);
  }
}(this, function(ApiClient, SiteMeta) {
  'use strict';

  /**
   * Site service.
   * @module api/SiteApi
   * @version 1.0.0
   */

  /**
   * Constructs a new SiteApi. 
   * @alias module:api/SiteApi
   * @class
   * @param {module:ApiClient} apiClient Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the siteGet operation.
     * @callback module:api/SiteApi~siteGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/SiteMeta} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Returns site setup status and meta information.   If site setup is complete, a 200 status code is returned with site information.   If site has not been setup yet, a 404 status is returned. 
     * @param {module:api/SiteApi~siteGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/SiteMeta}
     */
    this.siteGet = function(callback) {
      var postBody = null;


      var pathParams = {
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = SiteMeta;

      return this.apiClient.callApi(
        '/site', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
