/**
 * NodeCMS
 * API for Node Content Management System
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.NodeCms);
  }
}(this, function(expect, NodeCms) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new NodeCms.SiteMeta();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('SiteMeta', function() {
    it('should create an instance of SiteMeta', function() {
      // uncomment below and update the code to test SiteMeta
      //var instane = new NodeCms.SiteMeta();
      //expect(instance).to.be.a(NodeCms.SiteMeta);
    });

    it('should have the property setupRequired (base name: "setupRequired")', function() {
      // uncomment below and update the code to test the property setupRequired
      //var instane = new NodeCms.SiteMeta();
      //expect(instance).to.be();
    });

    it('should have the property siteTitle (base name: "siteTitle")', function() {
      // uncomment below and update the code to test the property siteTitle
      //var instane = new NodeCms.SiteMeta();
      //expect(instance).to.be();
    });

  });

}));
