/**
 * NodeCMS
 * API for Node Content Management System
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/SiteMeta', 'model/User', 'model/UserName', 'api/SiteApi', 'api/UserApi'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('./ApiClient'), require('./model/SiteMeta'), require('./model/User'), require('./model/UserName'), require('./api/SiteApi'), require('./api/UserApi'));
  }
}(function(ApiClient, SiteMeta, User, UserName, SiteApi, UserApi) {
  'use strict';

  /**
   * API_for_Node_Content_Management_System.<br>
   * The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
   * <p>
   * An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
   * <pre>
   * var NodeCms = require('index'); // See note below*.
   * var xxxSvc = new NodeCms.XxxApi(); // Allocate the API class we're going to use.
   * var yyyModel = new NodeCms.Yyy(); // Construct a model instance.
   * yyyModel.someProperty = 'someValue';
   * ...
   * var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
   * ...
   * </pre>
   * <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
   * and put the application logic within the callback function.</em>
   * </p>
   * <p>
   * A non-AMD browser application (discouraged) might do something like this:
   * <pre>
   * var xxxSvc = new NodeCms.XxxApi(); // Allocate the API class we're going to use.
   * var yyy = new NodeCms.Yyy(); // Construct a model instance.
   * yyyModel.someProperty = 'someValue';
   * ...
   * var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
   * ...
   * </pre>
   * </p>
   * @module index
   * @version 1.0.0
   */
  var exports = {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient: ApiClient,
    /**
     * The SiteMeta model constructor.
     * @property {module:model/SiteMeta}
     */
    SiteMeta: SiteMeta,
    /**
     * The User model constructor.
     * @property {module:model/User}
     */
    User: User,
    /**
     * The UserName model constructor.
     * @property {module:model/UserName}
     */
    UserName: UserName,
    /**
     * The SiteApi service constructor.
     * @property {module:api/SiteApi}
     */
    SiteApi: SiteApi,
    /**
     * The UserApi service constructor.
     * @property {module:api/UserApi}
     */
    UserApi: UserApi
  };

  return exports;
}));
